### ISSUE TITLE
PyPi里还是2020年的2.2.0

### ISSUE THREAD

**Issue by wsy** [wxpusher/wxpusher-sdk-python#10]
希望能把Feb2020之后的更新推上去

**Comment by huxuan** [comment]
到目前为止最新的修改都以 [2.3.0](https://pypi.org/project/wxpusher/2.3.0/) 发布了，不过可能功能性上还有些问题，后续我会抽时间维护一下。

有任何具体问题欢迎报 issue，正好可以针对性的修。
