### ISSUE TITLE
itchat早就凉了吧

### ISSUE THREAD

**Issue by s192516** [wxpusher/wxpusher-sdk-python#11]
所有基于itchat的项目都不能用了, 不明白还更新啥, 骗我点进来

**Comment by huxuan** [comment]
wxpusher 这个服务至少到目前为止一直是可用的，不过这个 Python SDK 确实没有很好维护，最近我会抽一点时间整一下，感谢 push

**Comment by s192516** [comment]
非常感谢回复, 如果能更新python版本真的是万分感谢了, 我还是个新手技术很菜如果我可以帮帮到忙的话, 我非常愿意, 邮件不常看回复慢了
